### PR TITLE
Initargs

### PR DESCRIPTION
**Pull request by rherault-insa**
Add possibility to change escape char + public var can be change by calling the constructor

### CODE REVIEW

**Comment by evanplaice** [comment]
Does this PR supercede #1?

**Comment by rherault-insa** [comment]
Yes if you will, by having two PRs I let you the choice to integrate just one new functionnality at the time

**Comment by evanplaice** [comment]
Gotcha. It makes sense to expose this option to the CLI if it's available for use in the library.

**Comment by rherault-insa** [comment]
I don't understand what you are asking ?

**Comment by evanplaice** [comment]
Scratch that last comment, cc7d78c exposes the options via the constructor.

Would you mind changing the following?

*From:*
```python
self.input = inFile
self.output = outFile
```

*To:*
```python
self.input = input
self.output = output
```

I, prefer to keep the API consistent wherever possible.

**Comment by rherault-insa** [comment]
The problem is that "input" is a builtin function name and I'm not at ease giving this name to a parameter, it may cause problem.
Like 
```python
input = 'toto'
parser=preprocessor(input=input)
```
May prevent following call to the built-in python function.

**Comment by evanplaice** [comment]
You're right.

I'd prefer to rename the method members too but that would constitute a breaking change to the API. I'll merge this for now and clean up the rest later.

Ref https://github.com/evanplaice/pypreprocessor/issues/3

Thanks for the contribution.

**Pull request merged**
