### PR TITLE
Added some test and fixed some problems with cleanups

### PR DESCRIPTION
**Pull request by Epikem**
I added some tests and fixed some problems including what i made. Tested on Windows, Python 2.7 and 3.6

pypreprocessor __init__.py
Fixed some problems and cleanups
 + increased version to 0.76
	did for setup.py install and test. no big meaning
 * changed open to io.open for python2 compatibility
	open with encoding option raises error on python2
 * forced deprecation warnings to show
	deprecation warning was ignored as default
 * made deprecated values be used only if corresponding alternative is default value
 * moved __reset_internal statement to beginning of parse start
 * added exception handler to unclosed #ifdef block warning input
	if i enter without typing anything, it raises error.
 * cleanup post_process
 * removed return statement on line 290
	to make sure post_process finish process executed (check resume and check save).
	This will be a wrong fix if it should not be resumed. I don't know what override_import does and when it will be run. Please take a look for this.
 * added local variable f on on_the_fly to prevent unclosed file error
	unclosed file error raised when testing
 
other files
Added some tests
 + added RunTests command to setup.py
 + added tests, tests/.isolated folder
 + added maintest and deprecationtest. deprecationtest is commented out because of print
	maintest.py has test template which contains all run mode for other test cases
	maintest has two test case : file parse test and capture print test. both parses parsetarget.py
 + added parsetarget.py
 * moved test.py to tests/.isolated and renamed to directiveTest.py

I found a problem which I could not fix and  it occurs on release versions also. #14

### CODE REVIEW

**Comment by evanplaice** [comment]
Awesome to see tests. Quick question, why add testing to setup.py? I'm not familiar with that convention.

**Comment by evanplaice** [comment]
Made two minor chages

I removed testing from the MANIFEST. Tests are for development, the bundle published to PYPI should be 'production ready' meaning it should only contain the minimum contents required to run it.

I added your name to the LICENSE.

**Comment by evanplaice** [comment]
One other note, if you update the version number, use semver format [major].[feature].[patch].

The latest is published as 0.7.7. I'm working on adding Travis-CI integration but there are some permission snags due to pypreprocessor being registered under the Interpreters org.

**Comment by Epikem** [comment]
I got it. Thanks!

**Pull request merged**
